jobs:
  include:
    - stage: test
      language: python
      python:
        - 3.8.0
      before_install:
        - cd backend/todo_api
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test
    - stage: test
      language: node_js
      node_js:
        - '14.13.1'
      before_install:
        - cd frontend
      install:
        - npm ci
        - npm run build
      script:
        - npm run test
notifications:
  email: false
