jobs:
  include:
    - stage: test
      language: python
      python:
        - 3.6
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test
    - stage: test
      language: node_js
      node_js:
        - '10'
      before_install:
        - cd frontend
      install:
        - npm ci
        - npm run build
      script:
        - npm run test
    - stage: deploy
      if: branch = production
      language: node_js
      node_js:
        - '10'
      script: bash deploy/deploy.sh
notifications:
  email: false
